# Twitter OAuth Setting
twitter_key:    <%= ENV['TWITTER_KEY'] %>
twitter_secret: <%= ENV['TWITTER_SECRET'] %>

# Facebook OAuth Setting
facebook_app_id:     <%= ENV['FACEBOOK_APP_ID'] %>
facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>

# GitHub OAuth Setting
github_client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
github_secret:    <%= ENV['GITHUB_SECRET'] %>

# Facebook App ID
facebook_app_id: '1443747899201804'

# Gmail Pass
mail_password: <%= ENV['MAIL_PASSWORD'] %>

secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

# YouTube
youtube_api_key: <%= ENV['YOUTUBE_API_KEY'] %>
